batch_size: 256
clip_gradient_norm: 1
commit_hash: e4329c3
data_dir: processed_data
dataset: generic
dev_mode: true
device: cuda:0
dynamic_inputs:
- pr_x
- tmax_x
- tmin_x
epochs: 200
experiment_name: molstm_attn_learnable_temp_gating
head: regression
hidden_size: 32
img_log_dir: 
  /home/ycjc0331/neuralhydrology/examples/07-CDEC/runs/molstm_attn_learnable_temp_gating_1210_044554/img_log
initial_forget_bias: 3
learning_rate: 0.01
log_interval: 5
log_n_figures: 1
log_tensorboard: false
loss: MSE
metrics:
- NSE
- MSE
model: moe_lstm_attn_learnable_temp_gating
num_workers: 4
number_of_basins: 14
optimizer: AdamW
output_activation: linear
output_dropout: 0.4
package_version: 1.10.0
predict_last_n: 1
run_dir: 
  /home/ycjc0331/neuralhydrology/examples/07-CDEC/runs/molstm_attn_learnable_temp_gating_1210_044554
save_weights_every: 1
seed: 892733
seq_length: 365
static_attributes:
- MEAN_Elev
- MAX_Elev
- SD_Elev
- Percent_Area_Land_0
- Percent_Area_Land_1
- Percent_Area_Land_4
- Percent_Area_Land_5
- Percent_Area_Land_6
- Percent_Area_Land_7
- Percent_Area_Land_8
- Percent_Area_Land_9
- Percent_Area_Land_10
- Percent_Area_Land_11
- Percent_Area_Land_14
target_variables:
- discharge
test_basin_file: cdec_nondet_basin.txt
test_end_date: 31/12/2018
test_start_date: 01/01/2013
train_basin_file: cdec_nondet_basin.txt
train_dir: 
  /home/ycjc0331/neuralhydrology/examples/07-CDEC/runs/molstm_attn_learnable_temp_gating_1210_044554/train_data
train_end_date: 31/12/2012
train_start_date: 01/10/1987
validate_every: 50
validate_n_random_basins: 1
validation_basin_file: cdec_nondet_basin.txt
validation_end_date: 31/12/2012
validation_start_date: 01/01/2009
